### ISSUE TITLE
Add CODEOWNERS file

### ISSUE THREAD

**Issue by rbradford** [rust-vmm/linux-loader#1]
Please add a CODEOWNERS file with the details of the maintainers. Please use the following format as outlined in: https://help.github.com/en/articles/about-code-owners

Most projects can simply follow the wildcard syntax. e.g.

`* @owner1 @owner2`

Not only does this provide a way to see who is responsible or this repository they will also automatically be notified of incoming PR reviews.

**Comment by aghecenco** [comment]
#7 adds the `PullAssigner` bot; will that do or do you prefer individual entries?

**Comment by andreeaflorescu** [comment]
I think it's better for crates to have dedicated owners.

**Comment by aghecenco** [comment]
@bjzhjing @sameo @rbradford you 3 and I are the top 4 contributors so far. Do any of you want to be codeowners?

**Comment by bjzhjing** [comment]
@aghecenco Thanks for asking! Yes, please help add me.
