### ISSUE TITLE
Group errors per feature

### ISSUE THREAD

**Issue by aghecenco** [rust-vmm/linux-loader#22]
Per @andreeaflorescu's observation, the loader module currently has one `Error` type for all kernel loading issues: https://github.com/rust-vmm/linux-loader/blob/0c754f380acaa905e764a6a41175275cbc7d761b/src/loader/mod.rs#L51
This should be split per-feature; for instance, a vmm build only with bzImage support doesn't need to care about elf loading errors.

**Comment by andreeaflorescu** [comment]
We could also keep them in the same `Error` enum and compile them out.
