### ISSUE TITLE
Replace include_bytes with opening files

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/linux-loader#65]
To simplify the unit tests, we can replace `include_bytes` with just sending the file as a parameter.

We can remove all `make*` functions in [src/loader/x86_64/elf/mod.rs](https://github.com/rust-vmm/linux-loader/blob/master/src/loader/x86_64/elf/mod.rs#L402) and just call the load functions with the file.

**Comment by ahmedaabouzied** [comment]
@andreeaflorescu Hey is this still relevant? I can work on it if it's up for grabs.

**Comment by andreeaflorescu** [comment]
Ah, no, I should close this one. Sorry about that. Would you like to work on another one?

**Comment by ahmedaabouzied** [comment]
@andreeaflorescu yea sure. If you could point towards another available ticket, I'd gladly give it a try.

**Comment by andreeaflorescu** [comment]
@ahmedaabouzied I pinged you on Slack.
