### ISSUE TITLE
[Bug] Parsing elf notes does not use the System V ABI spec recommended alignment

### ISSUE THREAD

**Issue by iulianbarbu** [rust-vmm/linux-loader#71]
Currently, when parsing elf notes, the code relies on an alignment coming from the program header `p_align` [1]. This alignment is used for elf segments alignment [2]. For the elf notes fields alignment the specification/toolchain implementations make use of other alignments [3].

The proposal would be to use the right alignment while parsing through the elf notes. What is right is a complex discussion, which implies approaches which do/or do not entirely follow the System V ABI. An assumption that we can make, that linux also has made, it is to always consider the elf notes alignment to be 4 bytes, but this is very dependent on the build toolchain used to produce the ELF binary. So even if the crate is called linux-loader, it is not necessarily the case to follow how linux kernel/applications handle this problem, but it is definitely a starting point.

[1] https://github.com/rust-vmm/linux-loader/blob/master/src/loader/x86_64/elf/mod.rs#L346-L347 and https://github.com/rust-vmm/linux-loader/blob/master/src/loader/x86_64/elf/mod.rs#L369.
[2] https://man7.org/linux/man-pages/man5/elf.5.html
[3] https://github.com/rust-vmm/linux-loader/pull/70#discussion_r589445984

**Comment by zhuangel** [comment]
Same issue found here [https://github.com/rust-vmm/vm-virtio/pull/220#issuecomment-1397350320](url) , the issue will cause linux v6.0 and v6.1 boot failed. cc @rbradford

**Comment by rbradford** [comment]
I think I found the source of the problem. From the spec

```
       Note sections contain a series of notes (see the struct
       definitions below).  Each note is followed by the name field
       (whose length is defined in n_namesz) and then by the descriptor
       field (whose length is defined in n_descsz) and whose starting
       address has a 4 byte alignment.  Neither field is defined in the
       note struct due to their arbitrary lengths.
```

note descriptors should be 4 byte aligned not aligned based on `p_align`. `p_align` is for the alignment of sections. I can see that depending on compiler, kernel binary size, etc, that the note could also end up being aligned to the same value a p_align by coincidence.

Do you want to create a PR to fix this?

**Comment by zhuangel** [comment]
@rbradford  sorry for the late reply, I have created a fix PR for this issue :)
